export default {
  INPUT_CHANGE: 'INPUT_CHANGE',
  FORM_SUBMIT: 'FORM_SUBMIT', // delete later
  FIND_SUBSCRIBER_REQUEST: 'FIND_SUBSCRIBER_REQUEST',
  FIND_SUBSCRIBER_SUCCESS: 'FIND_SUBSCRIBER_SUCCESS',
  FIND_SUBSCRIBER_FAILURE: 'FIND SUBSCRIBER_FAILURE',

}