export default {
  INPUT_CHANGE: 'INPUT_CHANGE',
  FORM_SUBMIT: 'FORM_SUBMIT', // delete later
  FIND_SUBSCRIBER_REQUEST: 'FIND_SUBSCRIBER_REQUEST',
  FIND_SUBSCRIBER_SUCCESS: 'FIND_SUBSCRIBER_SUCCESS',
  FIND_SUBSCRIBER_FAILURE: 'FIND SUBSCRIBER_FAILURE',
  FIND_SUBSCRIBERS_INFO_REQUEST: 'FIND_SUBSCRIBERS_INFO_REQUEST',
  FIND_SUBSCRIBERS_INFO_SUCCESS: 'FIND_SUBSCRIBERS_INFO_SUCCESS',
  FIND_SUBSCRIBERS_INFO_FAILURE: 'FIND_SUBSCRIBERS_INFO_FAILURE',
}