export default {
  INPUT_CHANGE: 'INPUT_CHANGE',
  FORM_SUBMIT: 'FORM_SUBMIT', // delete later
  FIND_SUBSCRIBER_REQUEST: 'ADD_FIND_SUBSCRIBER_REQUEST',
  FIND_SUBSCRIBER_SUCCESS: 'ADD_FIND_SUBSCRIBER_SUCCESS',
  FIND_SUBSCRIBER_FAILURE: 'ADD_FIND_SUBSCRIBER_FAILURE',
  UPDATE_FIND_SUBSCRIBER_CURRENT_JOB_SUCCESS: 'UPDATE_FIND_SUBSCRIBER_CURRENT_JOB_SUCCESS',
  UPDATE_FIND_SUBSCRIBER_CURRENT_JOB_FAILURE: 'UPDATE_FIND_SUBSCRIBER_CURRENT_JOB_FAILURE',
  UPDATE_FIND_SUBSCRIBER_OTHER_JOB_SUCCESS: 'UPDATE_FIND_SUBSCRIBER_OTHER_JOB_SUCCESS',
  UPDATE_FIND_SUBSCRIBER_OTHER_JOB_FAILURE: 'UPDATE_FIND_SUBSCRIBER_OTHER_JOB_FAILURE'
}