export default {
  INPUT_CHANGE: 'INPUT_CHANGE',
  FORM_SUBMIT: 'FORM_SUBMIT', // delete later
  ADD_FIND_SUBSCRIBER_JOB_REQUEST: 'ADD_FIND_SUBSCRIBER_JOB_REQUEST',
  ADD_FIND_SUBSCRIBER_JOB_SUCCESS: 'ADD_FIND_SUBSCRIBER_JOB_SUCCESS',
  ADD_FIND_SUBSCRIBER_JOB_FAILURE: 'ADD_FIND_SUBSCRIBER_JOB_FAILURE',
  UPDATE_FIND_SUBSCRIBER_CURRENT_JOB_SUCCESS: 'UPDATE_FIND_SUBSCRIBER_CURRENT_JOB_SUCCESS',
  UPDATE_FIND_SUBSCRIBER_CURRENT_JOB_FAILURE: 'UPDATE_FIND_SUBSCRIBER_CURRENT_JOB_FAILURE',
  UPDATE_FIND_SUBSCRIBER_OTHER_JOB_SUCCESS: 'UPDATE_FIND_SUBSCRIBER_OTHER_JOB_SUCCESS',
  UPDATE_FIND_SUBSCRIBER_OTHER_JOB_FAILURE: 'UPDATE_FIND_SUBSCRIBER_OTHER_JOB_FAILURE',
  CLEAR_GENERAL_ERROR_MESSAGE: 'CLEAR_GENERAL_ERROR_MESSAGE'
}